from __future__ import annotations

DEMO_COMPANY = ("DEMO HOLDİNG A.Ş.", "DEMOH", "demo-oid-0000")

DEMO_DISCLOSURES = [
    {
        "index": "9000001",
        "publish_datetime": "2026-04-22 17:14:00",
        "company_name": "DEMO HOLDİNG A.Ş.",
        "stock_codes": "DEMOH",
        "subject": "Kar Payı Dağıtımı",
        "category": "Temettü",
        "summary": "Yönetim kurulu, 2025 yılı net dönem karından brüt %18 nakit kar payı dağıtılmasına karar verdi.",
        "type": "Olağan",
        "has_attachment": True,
        "is_late": False,
        "is_corrective": False,
        "url": "https://www.kap.org.tr/tr/Bildirim/9000001",
        "page_text": "Yönetim Kurulu Karar Tarihi 22.04.2026. Ödenmiş sermaye 1.000.000.000 TL. Brüt kar payı oranı %18, net %16,2.",
    },
    {
        "index": "9000002",
        "publish_datetime": "2026-04-15 09:02:00",
        "company_name": "DEMO HOLDİNG A.Ş.",
        "stock_codes": "DEMOH",
        "subject": "2025 Yılı Konsolide Finansal Rapor",
        "category": "Finansal Rapor",
        "summary": "2025 yılı 4. çeyrek konsolide bilanço ve gelir tablosu KAP'a sunuldu.",
        "type": "Periyodik",
        "has_attachment": True,
        "is_late": False,
        "is_corrective": False,
        "url": "https://www.kap.org.tr/tr/Bildirim/9000002",
        "page_text": "Hasılat: 12.450.000.000 TL. Net dönem karı: 1.820.000.000 TL. Faaliyet karı: 2.310.000.000 TL.",
    },
    {
        "index": "9000003",
        "publish_datetime": "2026-03-30 11:42:00",
        "company_name": "DEMO HOLDİNG A.Ş.",
        "stock_codes": "DEMOH",
        "subject": "Olağan Genel Kurul Toplantı Çağrısı",
        "category": "Genel Kurul",
        "summary": "Olağan genel kurul toplantısı 28 Mayıs 2026 tarihinde yapılacaktır.",
        "type": "Olağan",
        "has_attachment": False,
        "is_late": False,
        "is_corrective": False,
        "url": "https://www.kap.org.tr/tr/Bildirim/9000003",
        "page_text": "Toplantı yer ve zamanı, gündem maddeleri ve vekaletname örneği ek dosyada yer almaktadır.",
    },
    {
        "index": "9000004",
        "publish_datetime": "2026-03-12 14:08:00",
        "company_name": "DEMO HOLDİNG A.Ş.",
        "stock_codes": "DEMOH",
        "subject": "Yeni Sözleşme - Altyapı Projesi",
        "category": "Sözleşme/İhale",
        "summary": "Şirketimiz 850 milyon TL bedelli yeni bir altyapı sözleşmesi imzalamıştır.",
        "type": "Özel Durum",
        "has_attachment": False,
        "is_late": False,
        "is_corrective": False,
        "url": "https://www.kap.org.tr/tr/Bildirim/9000004",
        "page_text": "Sözleşme süresi 24 ay olup proje 2028 yılına kadar tamamlanacaktır.",
    },
]
